name: Build and Upload Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate a File
      run: |
        mkdir -p output
        echo "This is an artifact file Of SAHIL THAKUR!" > output/hello.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: output/
